name: dyndns_client
description: A DynDNS Desktop client

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  ddns_client:
    git:
      url: 'https://github.com/danrubel/ddns_client.dart'
      ref: 'c92d68f'
  flutter_secure_storage: ^6.0.0
  intl: ^0.17.0
  logger: ^1.1.0
  synchronized: ^3.0.0+2
  system_tray: ^2.0.1
  bitsdojo_window: 0.1.2
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  msix: ^3.5.1

flutter:
  uses-material-design: true

  assets:
    - assets/app_icon.ico
    - assets/app_icon.png

msix_config:
  display_name: DynDNS Client
  publisher_display_name: MarkusJx
  identity_name: com.markusjx.dyndnsclient
  msix_version: 1.0.0.0
  logo_path: assets/app_icon.png
  capabilities: internetClient