# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Flutter

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macOs-latest]
    runs-on: ${{matrix.os}}

    steps:
      - uses: actions/checkout@v3

      - name: Install Flutter
        uses: subosito/flutter-action@v2.4.0
        
      - name: Flutter pub get
        run: flutter pub get
        
      - name: Build windows
        run: flutter build windows
        if: matrix.os == 'windows-latest'
      - name: Build macos
        if: matrix.os == 'macOs-latest'
        run: |
          flutter config --enable-macos-desktop
          flutter doctor
          flutter build macos
        
      - name: Upload Build Artifact windows
        uses: actions/upload-artifact@v3.0.0
        if: matrix.os == 'windows-latest'
        with:
          name: dyndns_client-windows
          path: build/windows/runner/Release

      - name: Upload Build Artifact macos
        uses: actions/upload-artifact@v3.0.0
        if: matrix.os == 'macOs-latest'
        with:
          name: dyndns_client-macos
          path: build/macos/Build/Products/Release/dyndns_client
